version: '3.9'

services:
  db:
    image: postgres:14
    restart: "no"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: visorm
    ports:
      - "5432:5432"
    volumes:
      - ./database/pgdata:/var/lib/postgresql/data
