[server]
port = 8000
host = "0.0.0.0"

[database]
name = "postgres"
host = "localhost"
port = 5432
user = "postgres"
password = "postgres"

[[cors]]
origin = "http://localhost:3000"
methods = [ "GET", "POST", "PUT", "DELETE", "OPTIONS" ]
headers = [
  "Content-Type",
  "Authorization",
  "X-Requested-With",
  "X-HTTP-Method-Override",
  "Accept",
  "Accept-Version",
  "X-Api-Version",
  "X-File-Name"
]
exposedHeaders = [ "X-Api-Version", "X-Request-Id", "X-Response-Time" ]
credentials = true
maxAge = 3600
